### ISSUE TITLE
Add shields/badges to README.md

### ISSUE THREAD

**Issue by huenique** [SurPathHub/Dayong#10]
Shields or badges allow you to show the state of a project to users. Sometimes they also show how much effort and dedication are put into the project. For now, we want to show the python version (3.9 and above), license (MIT), ~~project version~~, and commit activity.

**Comment by avinash-tiwari** [comment]
@huenique please assign this issue to me, I wanna work on this.

**Comment by huenique** [comment]
@avinash-tiwari sure, go ahead!
