### ISSUE TITLE
Add Github Action to check with flake8

### ISSUE THREAD

**Issue by gitfort47** [SurPathHub/Dayong#14]

**Comment by huenique** [comment]
Yeah, we definitely could use that. @gitfort47 will you be working on this?

**Comment by huenique** [comment]
@OBITORASU you still interested in working on this?

**Comment by OBITORASU** [comment]
Sure thing I am still willing!

**Comment by huenique** [comment]
@OBITORASU Idk when the author is going to get back on this, so ig you're up
