### ISSUE TITLE
Migrate Dayong's design model and implement slash commands

### ISSUE THREAD

**Issue by huenique** [SurPathHub/Dayong#4]
The sole maintainer of discord.py has [ceased](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1) the development of their API wrapper. This is my first time making a complete discord bot, so I wasn't aware of this matter.

The reason I chose discord.py was because of its popularity and that it was a fast and mature library. Now that discord.py is essentially dead, we're left with a few options:

1. Rebuild the bot in another language.
2. Rebuild the bot with another library.
3. Extend discord.py to support slash commands.

If you read Danny's announcement, Discord is forcing bot developers to use slash commands. Dayong will die in 8 or 9 months if we continue using discord.py's design model.

Regarding our remaining options, from a project maintainer's point of view, the first one sounds like our top choice, but we don't have to abandon Python just yet. Personally, I think the second or third is our best option. For number 2, I'm looking into other libraries, such as [hikari](https://github.com/hikari-py/hikari), which is starting to gain traction after the announcement. For number 3, there's [discord-interactions](https://github.com/goverfl0w/discord-interactions), which is a discord.py extension for supporting slash commands.

**Comment by MatteuSan** [comment]
Go for #3
